/*
 *
 * TicketItems constants
 *
 */

export const UPDATE_TMP_TICKET_DATA_ACTION = 'ui/TicketItems/UPDATE_TMP_TICKET_DATA_ACTION';

export const UPDATE_STOCK_TICKET_DATA_ACTION = 'ui/TicketItems/UPDATE_STOCK_TICKET_DATA_ACTION';

export const REMOVE_STOCK_FROM_TICKET_ACTION = 'ui/TicketItems/REMOVE_STOCK_FROM_TICKET_ACTION';

export const ADD_STOCK_TO_TICKET_ACTION = 'ui/StockItems/ADD_STOCK_TO_TICKET_ACTION';

export const UPDATE_TICKET_ACTION = 'ui/TicketItems/UPDATE_TICKET_ACTION';
export const UPDATE_TICKET_SUCCESS_ACTION = 'ui/TicketItems/UPDATE_TICKET_SUCCESS_ACTION';
export const UPDATE_TICKET_ERROR_ACTION = 'ui/TicketItems/UPDATE_TICKET_ERROR_ACTION';
