/*
 *
 * TicketItems constants
 *
 */

export const UPDATE_TMP_TICKET_DATA_ACTION = 'ui/TicketItems/UPDATE_TMP_TICKET_DATA_ACTION';

export const UPDATE_STOCK_TICKET_DATA_ACTION = 'ui/TicketItems/UPDATE_STOCK_TICKET_DATA_ACTION';

export const REMOVE_STOCK_FROM_TICKET_ACTION = 'ui/TicketItems/REMOVE_STOCK_FROM_TICKET_ACTION';
export const REMOVE_TICKET_ACTION = 'ui/TicketItems/REMOVE_TICKET_ACTION';

export const LOAD_TICKET_ACTION = 'ui/TicketItems/LOAD_TICKET_ACTION';
export const LOAD_TICKET_ERROR_ACTION = 'ui/TicketItems/LOAD_TICKET_ERROR_ACTION';
export const LOAD_TICKET_SUCCESS_ACTION = 'ui/TicketItems/LOAD_TICKET_SUCCESS_ACTION';

export const ADD_STOCK_TO_TICKET_ACTION = 'ui/StockItems/ADD_STOCK_TO_TICKET_ACTION';

export const UPDATE_TICKET_ACTION = 'ui/TicketItems/UPDATE_TICKET_ACTION';
export const UPDATE_TICKET_SUCCESS_ACTION = 'ui/TicketItems/UPDATE_TICKET_SUCCESS_ACTION';
export const UPDATE_TICKET_ERROR_ACTION = 'ui/TicketItems/UPDATE_TICKET_ERROR_ACTION';

export const GET_MATCHES_TICKETS_ACTION = 'ui/TicketItems/GET_MATCHES_TICKETS_ACTION';
export const GET_MATCHES_TICKETS_ERROR_ACTION = 'ui/TicketItems/GET_MATCHES_TICKETS_ERROR_ACTION';
export const GET_MATCHES_TICKETS_SUCCESS_ACTION = 'ui/TicketItems/GET_MATCHES_TICKETS_SUCCESS_ACTION';

export const CLOSE_TICKET_ACTION = 'ui/TicketItems/CLOSE_TICKET_ACTION';
export const CLOSE_TICKET_SUCCESS_ACTION = 'ui/TicketItems/CLOSE_TICKET_SUCCESS_ACTION';
export const CLOSE_TICKET_ERROR_ACTION = 'ui/TicketItems/CLOSE_TICKET_ERROR_ACTION';

export const PRINT_TICKET_ACTION = 'ui/TicketItems/PRINT_TICKET_ACTION';
export const PRINT_TICKET_SUCCESS_ACTION = 'ui/TicketItems/PRINT_TICKET_SUCCESS_ACTION';
export const PRINT_TICKET_ERROR_ACTION = 'ui/TicketItems/PRINT_TICKET_ERROR_ACTION';

export const UPDATE_TICKET_TAX_ACTION = 'ui/TicketItems/UPDATE_TICKET_TAX_ACTION';
export const UPDATE_TICKET_DISCOUNT_ACTION = 'ui/TicketItems/UPDATE_TICKET_DISCOUNT_ACTION';

