/*
 *
 * TicketItems constants
 *
 */
export const ADD_STOCK_TO_TICKET_ACTION = 'ui/StockItems/ADD_STOCK_TO_TICKET_ACTION';
export const RETURN_ITEM_FROM_TICKET_ACTION = 'ui/StockItems/RETURN_ITEM_FROM_TICKET_ACTION';
export const REMOVE_STOCK_FROM_TICKET_ACTION = 'ui/StockItems/REMOVE_STOCK_FROM_TICKET_ACTION';
export const UPDATE_TICKET_OPERATION_ACTION = 'ui/tickets/UPDATE_OPERATION_ACTION';
export const UPDATE_TICKET_PAYMENT_ACTION = 'ui/tickets/UPDATE_TICKET_PAYMENT_ACTION';
export const ADD_VOUCHER_PAYMENT_AMOUNT_ACTION = 'ui/tickets/ADD_VOUCHER_PAYMENT_AMOUNT_ACTION';
export const ADD_VOUCHER_PAYMENT_AMOUNT_ERROR_ACTION = 'ui/tickets/ADD_VOUCHER_PAYMENT_AMOUNT_ERROR_ACTION';
export const ADD_VOUCHER_PAYMENT_AMOUNT_SUCCESS_ACTION = 'ui/tickets/ADD_VOUCHER_PAYMENT_AMOUNT_SUCCESS_ACTION';
export const REMOVE_VOUCHER_PAYMENT_AMOUNT_ACTION = 'ui/tickets/REMOVE_VOUCHER_PAYMENT_AMOUNT_ACTION';
export const CREATE_TICKET_ACTION = 'ui/tickets/CREATE_TICKET_ACTION';
export const CREATE_TICKET_SUCCESS_ACTION = 'ui/tickets/CREATE_TICKET_SUCCESS_ACTION';
export const LOAD_TICKET_ACTION = 'ui/tickets/LOAD_TICKET_ACTION';
export const LOAD_TICKET_SUCCESS_ACTION = 'ui/tickets/LOAD_TICKET_SUCCESS_ACTION';
export const LOAD_TICKET_ERROR_ACTION = 'ui/TicketItems/LOAD_TICKET_ERROR_ACTION';
export const CREATE_ADD_OPERATION_ACTION = 'ui/TicketItems/CREATE_ADD_OPERATION_ACTION';
export const CREATE_REMOVE_OPERATION_ACTION = 'ui/TicketItems/CREATE_REMOVE_OPERATION_ACTION';
export const GET_TICKET_MATCHES_ACTION = 'ui/TicketItems/GET_TICKET_MATCHES_ACTION';
export const GET_TICKET_MATCHES_ERROR_ACTION = 'ui/TicketItems/GET_TICKET_MATCHES_ERROR_ACTION';
export const GET_TICKET_MATCHES_SUCCESS_ACTION = 'ui/TicketItems/GET_TICKET_MATCHES_SUCCESS_ACTION';











export const UPDATE_TMP_TICKET_DATA_ACTION = 'ui/TicketItems/UPDATE_TMP_TICKET_DATA_ACTION';
export const UPDATE_STOCK_TICKET_DATA_ACTION = 'ui/TicketItems/UPDATE_STOCK_TICKET_DATA_ACTION';
export const REMOVE_TICKET_ACTION = 'ui/TicketItems/REMOVE_TICKET_ACTION';


export const UPDATE_TICKET_ACTION = 'ui/TicketItems/UPDATE_TICKET_ACTION';
export const UPDATE_TICKET_SUCCESS_ACTION = 'ui/TicketItems/UPDATE_TICKET_SUCCESS_ACTION';
export const UPDATE_TICKET_ERROR_ACTION = 'ui/TicketItems/UPDATE_TICKET_ERROR_ACTION';

export const GET_MATCHES_TICKETS_ACTION = 'ui/TicketItems/GET_MATCHES_TICKETS_ACTION';
export const GET_MATCHES_TICKETS_ERROR_ACTION = 'ui/TicketItems/GET_MATCHES_TICKETS_ERROR_ACTION';
export const GET_MATCHES_TICKETS_SUCCESS_ACTION = 'ui/TicketItems/GET_MATCHES_TICKETS_SUCCESS_ACTION';

export const CLOSE_TICKET_ACTION = 'ui/TicketItems/CLOSE_TICKET_ACTION';
export const CLOSE_TICKET_SUCCESS_ACTION = 'ui/TicketItems/CLOSE_TICKET_SUCCESS_ACTION';
export const CLOSE_TICKET_ERROR_ACTION = 'ui/TicketItems/CLOSE_TICKET_ERROR_ACTION';

export const PRINT_TICKET_ACTION = 'ui/TicketItems/PRINT_TICKET_ACTION';
export const PRINT_TICKET_SUCCESS_ACTION = 'ui/TicketItems/PRINT_TICKET_SUCCESS_ACTION';
export const PRINT_TICKET_ERROR_ACTION = 'ui/TicketItems/PRINT_TICKET_ERROR_ACTION';

export const UPDATE_TICKET_TAX_ACTION = 'ui/TicketItems/UPDATE_TICKET_TAX_ACTION';
export const UPDATE_TICKET_DISCOUNT_ACTION = 'ui/TicketItems/UPDATE_TICKET_DISCOUNT_ACTION';

export const SEARCH_TICKETS_ACTION = 'ui/TicketItems/SEARCH_TICKETS_ACTION';
export const SEARCH_TICKETS_ERROR_ACTION = 'ui/TicketItems/SEARCH_TICKETS_ERROR_ACTION';
export const SEARCH_TICKETS_SUCCESS_ACTION = 'ui/TicketItems/SEARCH_TICKETS_SUCCESS_ACTION';

