/*
 *
 * StockItems constants
 *
 */

export const DEFAULT_ACTION = 'app/StockItems/DEFAULT_ACTION';

export const CREATE_STOCK_ACTION = 'ui/StockItems/CREATE_STOCK_ACTION';
export const CREATE_STOCK_ERROR_ACTION =
  'ui/StockItems/CREATE_STOCK_ERROR_ACTION';
export const CREATE_STOCK_SUCCESS_ACTION =
  'ui/StockItems/CREATE_STOCK_SUCCESS_ACTION';

export const UPDATE_STOCK_ACTION = 'ui/StockItems/UPDATE_STOCK_ACTION';
export const UPDATE_STOCK_ERROR_ACTION =
  'ui/StockItems/UPDATE_STOCK_ERROR_ACTION';
export const UPDATE_STOCK_SUCCESS_ACTION =
  'ui/StockItems/UPDATE_STOCK_SUCCESS_ACTION';
export const START_STOCK_CHANGE_ACTION =
  'ui/StockItems/START_STOCK_CHANGE_ACTION';

export const REFRESH_STOCK_ACTION = 'ui/StockItems/REFRESH_STOCK_ACTION';
export const REFRESH_STOCK_ERROR_ACTION =
  'ui/StockItems/REFRESH_STOCK_ERROR_ACTION';
export const REFRESH_STOCK_SUCCESS_ACTION =
  'ui/StockItems/REFRESH_STOCK_SUCCESS_ACTION';

export const REMOVE_STOCK_ACTION = 'ui/StockItems/REMOVE_STOCK_ACTION';
export const REMOVE_STOCK_ERROR_ACTION =
  'ui/StockItems/REMOVE_STOCK_ERROR_ACTION';
export const REMOVE_STOCK_SUCCESS_ACTION =
  'ui/StockItems/REMOVE_STOCK_SUCCESS_ACTION';

export const EXPORT_STOCK_ACTION = 'ui/StockItems/EXPORT_STOCK_ACTION';
export const EXPORT_STOCK_ERROR_ACTION =
  'ui/StockItems/EXPORT_STOCK_ERROR_ACTION';
export const EXPORT_STOCK_SUCCESS_ACTION =
  'ui/StockItems/EXPORT_STOCK_SUCCESS_ACTION';

export const SEARCH_STOCK_ACTION = 'ui/StockItems/SEARCH_STOCK_ACTION';
export const SEARCH_STOCK_ERROR_ACTION =
  'ui/StockItems/SEARCH_STOCK_ERROR_ACTION';
export const SEARCH_STOCK_SUCCESS_ACTION =
  'ui/StockItems/SEARCH_STOCK_SUCCESS_ACTION';

export const GET_MATCHES_STOCK_ACTION =
  'ui/StockItems/GET_MATCHES_STOCK_ACTION';
export const GET_MATCHES_STOCK_ERROR_ACTION =
  'ui/StockItems/GET_MATCHES_STOCK_ERROR_ACTION';
export const GET_MATCHES_STOCK_SUCCESS_ACTION =
  'ui/StockItems/GET_MATCHES_STOCK_SUCCESS_ACTION';

export const UPDATE_TMP_STOCK_DATA_ACTION =
  'ui/StockItems/UPDATE_TMP_STOCK_DATA_ACTION';

export const UPDATE_STOCK_MODAL_OPTION_ACTION =
  'ui/StockItems/UPDATE_STOCK_MODAL_OPTION_ACTION';

export const FILE_EXTENSIONS_ALLOWED = ['json', 'yaml', 'csv'];

