/*
 *
 * TicketPayments constants
 *
 */

export const SET_METHOD_TICKET_PAYMENTS_ACTION =
  'ui/TicketPayments/SET_METHOD_TICKET_PAYMENTS_ACTION';
export const SET_METHOD_TICKET_PAYMENTS_ERROR_ACTION =
  'ui/TicketPayments/SET_METHOD_TICKET_PAYMENTS_ERROR_ACTION';
export const SET_METHOD_TICKET_PAYMENTS_SUCCESS_ACTION =
  'ui/TicketPayments/SET_METHOD_TICKET_PAYMENTS_SUCCESS_ACTION';
