/*
 *
 * StockItems constants
 *
 */

export const DEFAULT_ACTION = 'app/StockItems/DEFAULT_ACTION';
export const UPDATE_STOCK_ACTION = 'ui/StockItems/UPDATE_STOCK_ACTION';
export const UPDATE_STOCK_ERROR_ACTION = 'ui/StockItems/UPDATE_STOCK_ERROR_ACTION';
export const UPDATE_STOCK_SUCCESS_ACTION = 'ui/StockItems/UPDATE_STOCK_SUCCESS_ACTION';

export const REFRESH_STOCK_ACTION = 'ui/StockItems/REFRESH_STOCK_ACTION';
export const REFRESH_STOCK_ERROR_ACTION = 'ui/StockItems/REFRESH_STOCK_ERROR_ACTION';
export const REFRESH_STOCK_SUCCESS_ACTION = 'ui/StockItems/REFRESH_STOCK_SUCCESS_ACTION';

export const REMOVE_STOCK_ACTION = 'ui/StockItems/REMOVE_STOCK_ACTION';
export const REMOVE_STOCK_ERROR_ACTION = 'ui/StockItems/REMOVE_STOCK_ERROR_ACTION';
export const REMOVE_STOCK_SUCCESS_ACTION = 'ui/StockItems/REMOVE_STOCK_SUCCESS_ACTION';
