name: unit-tests

on: 
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: node ${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CI: true
      NODE_ENV: test
    strategy:
      matrix:
        node-version: [12]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn@1
      - run: yarn --frozen-lockfile
      - run: yarn run test:ci